# Generated by Django 5.0.6 on 2024-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
